//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMI.Properties.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow use of GPS location.
        /// </summary>
        public static string AllowGPSUse {
            get {
                return ResourceManager.GetString("AllowGPSUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add favorite.
        /// </summary>
        public static string AppBar_AddToFavorites {
            get {
                return ResourceManager.GetString("AppBar_AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose city.
        /// </summary>
        public static string AppBar_ChooseCity {
            get {
                return ResourceManager.GetString("AppBar_ChooseCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string AppBar_Favorites {
            get {
                return ResourceManager.GetString("AppBar_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to me.
        /// </summary>
        public static string AppBar_GoToLocation {
            get {
                return ResourceManager.GetString("AppBar_GoToLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support.
        /// </summary>
        public static string AppBar_Support {
            get {
                return ResourceManager.GetString("AppBar_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Name: .
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEATHER FORECAST FROM DMI.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather Forecast from DMI.
        /// </summary>
        public static string AppTitleSmall {
            get {
                return ResourceManager.GetString("AppTitleSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beach Weather.
        /// </summary>
        public static string BeachWeatherMenuItem {
            get {
                return ResourceManager.GetString("BeachWeatherMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city weather.
        /// </summary>
        public static string CityWeatherHeader {
            get {
                return ResourceManager.GetString("CityWeatherHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to country.
        /// </summary>
        public static string CountryHeader {
            get {
                return ResourceManager.GetString("CountryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by: .
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write comments or technical questions to: email: 10229@iha.dk.
        /// </summary>
        public static string EmailHelpText {
            get {
                return ResourceManager.GetString("EmailHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string FavoritesHeader {
            get {
                return ResourceManager.GetString("FavoritesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve the location, because Location Servies aren&apos;t enabled..
        /// </summary>
        public static string GPSDisabledError {
            get {
                return ResourceManager.GetString("GPSDisabledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location service (GPS) in DMI City Weather is sending your current location to a cloud service in order to convert the geographical coordinates into a postal code. The location is then used to display the weather-information for your area..
        /// </summary>
        public static string GPSHelpText {
            get {
                return ResourceManager.GetString("GPSHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve the location..
        /// </summary>
        public static string GPSResolveError {
            get {
                return ResourceManager.GetString("GPSResolveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection is available. Please try again later..
        /// </summary>
        public static string InternetError {
            get {
                return ResourceManager.GetString("InternetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diverse.
        /// </summary>
        public static string MapsHeader {
            get {
                return ResourceManager.GetString("MapsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to news and tv.
        /// </summary>
        public static string NewsHeader {
            get {
                return ResourceManager.GetString("NewsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pollen.
        /// </summary>
        public static string PollenHeader {
            get {
                return ResourceManager.GetString("PollenHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.dk/dmi/radaranim2.gif.
        /// </summary>
        public static string RadarAnimation {
            get {
                return ResourceManager.GetString("RadarAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radar (rain).
        /// </summary>
        public static string RadarHeaderSmall {
            get {
                return ResourceManager.GetString("RadarHeaderSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar (rain).
        /// </summary>
        public static string RadarMenuItem {
            get {
                return ResourceManager.GetString("RadarMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regional.
        /// </summary>
        public static string RegionalHeader {
            get {
                return ResourceManager.GetString("RegionalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove favorite.
        /// </summary>
        public static string RemoveFavorite {
            get {
                return ResourceManager.GetString("RemoveFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send email.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support.
        /// </summary>
        public static string SupportHeader {
            get {
                return ResourceManager.GetString("SupportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://servlet.dmi.dk/byvejr/servlet/byvejr_dag1?by={0}&amp;tabel=dag1&amp;mode=long.
        /// </summary>
        public static string TemperatureImageSource {
            get {
                return ResourceManager.GetString("TemperatureImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://servlet.dmi.dk/byvejr/servlet/byvejr?by={0}&amp;tabel=dag1&amp;param=bolger.
        /// </summary>
        public static string WavesImageSource {
            get {
                return ResourceManager.GetString("WavesImageSource", resourceCulture);
            }
        }
    }
}
