//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMI.Properties.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tilføj favorit.
        /// </summary>
        public static string AppBar_AddToFavorites {
            get {
                return ResourceManager.GetString("AppBar_AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vælg by.
        /// </summary>
        public static string AppBar_ChooseCity {
            get {
                return ResourceManager.GetString("AppBar_ChooseCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favoritter.
        /// </summary>
        public static string AppBar_Favorites {
            get {
                return ResourceManager.GetString("AppBar_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vejret her.
        /// </summary>
        public static string AppBar_GoToLocation {
            get {
                return ResourceManager.GetString("AppBar_GoToLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEJRUDSIGTEN FRA DMI.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://servlet.dmi.dk/byvejr/servlet/byvejr_dag1?by={0}&amp;mode=long.
        /// </summary>
        public static string CityWeather2daysGraph {
            get {
                return ResourceManager.GetString("CityWeather2daysGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://servlet.dmi.dk/byvejr/servlet/byvejr?by={0}&amp;tabel=dag3_9.
        /// </summary>
        public static string CityWeather7daysGraph {
            get {
                return ResourceManager.GetString("CityWeather7daysGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byvejr.
        /// </summary>
        public static string CityWeatherHeader {
            get {
                return ResourceManager.GetString("CityWeatherHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favoritter.
        /// </summary>
        public static string FavoritesHeader {
            get {
                return ResourceManager.GetString("FavoritesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nyheder.
        /// </summary>
        public static string NewsHeader {
            get {
                return ResourceManager.GetString("NewsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.dk/dmi/pollen-feed.xml.
        /// </summary>
        public static string PollenFeed {
            get {
                return ResourceManager.GetString("PollenFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://servlet.dmi.dk/byvejr/servlet/pollen_dag1?by={0}.
        /// </summary>
        public static string PollenGraph {
            get {
                return ResourceManager.GetString("PollenGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pollental.
        /// </summary>
        public static string PollenHeader {
            get {
                return ResourceManager.GetString("PollenHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fjern favorit.
        /// </summary>
        public static string RemoveFavorite {
            get {
                return ResourceManager.GetString("RemoveFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.dk/dmi/rss-nyheder.
        /// </summary>
        public static string RssFeed {
            get {
                return ResourceManager.GetString("RssFeed", resourceCulture);
            }
        }
    }
}
