//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.468
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add live tile.
        /// </summary>
        public static string AddLiveTile {
            get {
                return ResourceManager.GetString("AddLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow use of GPS location.
        /// </summary>
        public static string AllowGPSUse {
            get {
                return ResourceManager.GetString("AllowGPSUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add favorite.
        /// </summary>
        public static string AppBar_AddToFavorites {
            get {
                return ResourceManager.GetString("AppBar_AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose city.
        /// </summary>
        public static string AppBar_ChooseCity {
            get {
                return ResourceManager.GetString("AppBar_ChooseCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string AppBar_Favorites {
            get {
                return ResourceManager.GetString("AppBar_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to me.
        /// </summary>
        public static string AppBar_GoToLocation {
            get {
                return ResourceManager.GetString("AppBar_GoToLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to live tile.
        /// </summary>
        public static string AppBar_LiveTile {
            get {
                return ResourceManager.GetString("AppBar_LiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new tile.
        /// </summary>
        public static string AppBar_NewTile {
            get {
                return ResourceManager.GetString("AppBar_NewTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support.
        /// </summary>
        public static string AppBar_Support {
            get {
                return ResourceManager.GetString("AppBar_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application:.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMI Byvejr Support.
        /// </summary>
        public static string AppSupportEmailHeader {
            get {
                return ResourceManager.GetString("AppSupportEmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEATHER FORECAST FROM DMI.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMI Byvejr.
        /// </summary>
        public static string AppTitleSmall {
            get {
                return ResourceManager.GetString("AppTitleSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beach Weather.
        /// </summary>
        public static string BeachWeatherMenuItem {
            get {
                return ResourceManager.GetString("BeachWeatherMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city weather.
        /// </summary>
        public static string CityWeatherHeader {
            get {
                return ResourceManager.GetString("CityWeatherHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denmark.
        /// </summary>
        public static string Country_Denmark {
            get {
                return ResourceManager.GetString("Country_Denmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faroe Islands.
        /// </summary>
        public static string Country_FaroeIslands {
            get {
                return ResourceManager.GetString("Country_FaroeIslands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenland.
        /// </summary>
        public static string Country_Greenland {
            get {
                return ResourceManager.GetString("Country_Greenland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to country.
        /// </summary>
        public static string CountryHeader {
            get {
                return ResourceManager.GetString("CountryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by: .
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thedeathart@gmail.com.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write comments or technical questions to thedeathart@gmail.com.
        /// </summary>
        public static string EmailHelpText {
            get {
                return ResourceManager.GetString("EmailHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string FavoritesHeader {
            get {
                return ResourceManager.GetString("FavoritesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve the location, because Location Servies aren&apos;t enabled..
        /// </summary>
        public static string GPSDisabledError {
            get {
                return ResourceManager.GetString("GPSDisabledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location service (GPS) in DMI City Weather is sending your current location to a cloud service in order to convert the geographical coordinates into a postal code. The location is then used to display the weather-information for your area..
        /// </summary>
        public static string GPSHelpText {
            get {
                return ResourceManager.GetString("GPSHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve the location..
        /// </summary>
        public static string GPSResolveError {
            get {
                return ResourceManager.GetString("GPSResolveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to live tile.
        /// </summary>
        public static string Header_LiveTile {
            get {
                return ResourceManager.GetString("Header_LiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uv index.
        /// </summary>
        public static string Header_UVIndex {
            get {
                return ResourceManager.GetString("Header_UVIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection is available. Please try again later..
        /// </summary>
        public static string InternetError {
            get {
                return ResourceManager.GetString("InternetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest ({0:HH&apos;:&apos;mm}).
        /// </summary>
        public static string LatestTitle {
            get {
                return ResourceManager.GetString("LatestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diverse.
        /// </summary>
        public static string MapsHeader {
            get {
                return ResourceManager.GetString("MapsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to news and tv.
        /// </summary>
        public static string NewsHeader {
            get {
                return ResourceManager.GetString("NewsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no regional forecast for your region..
        /// </summary>
        public static string NoRegionalForecast {
            get {
                return ResourceManager.GetString("NoRegionalForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodically checks for weather updates and updates the tile on the start screen..
        /// </summary>
        public static string PeriodicTaskHelpMessage {
            get {
                return ResourceManager.GetString("PeriodicTaskHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on a tile to pin it to your home screen..
        /// </summary>
        public static string PinToHomeHelpText {
            get {
                return ResourceManager.GetString("PinToHomeHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{1} hours ({0:HH&apos;:&apos;mm}).
        /// </summary>
        public static string PlusTitleTitle {
            get {
                return ResourceManager.GetString("PlusTitleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pollen.
        /// </summary>
        public static string PollenHeader {
            get {
                return ResourceManager.GetString("PollenHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radar (rain).
        /// </summary>
        public static string RadarHeaderSmall {
            get {
                return ResourceManager.GetString("RadarHeaderSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar (rain).
        /// </summary>
        public static string RadarMenuItem {
            get {
                return ResourceManager.GetString("RadarMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pictures are updated every 10th minute, and shows rain and snow over Denmark..
        /// </summary>
        public static string RadarPageHelpText1 {
            get {
                return ResourceManager.GetString("RadarPageHelpText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During a stable high pressure weather radarwaves can reflect in a warm layer of air in the atmosphere, so it hits the air or the sea, instead of the skies. In these cases, fake rainy areas will appear on the pictures..
        /// </summary>
        public static string RadarPageHelpText2 {
            get {
                return ResourceManager.GetString("RadarPageHelpText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regional.
        /// </summary>
        public static string RegionalHeader {
            get {
                return ResourceManager.GetString("RegionalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove favorite.
        /// </summary>
        public static string RemoveFavorite {
            get {
                return ResourceManager.GetString("RemoveFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send email.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support.
        /// </summary>
        public static string SupportHeader {
            get {
                return ResourceManager.GetString("SupportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Time Tile.
        /// </summary>
        public static string Tile_CustomTile {
            get {
                return ResourceManager.GetString("Tile_CustomTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to customize display time.
        /// </summary>
        public static string Tile_TapToCustom {
            get {
                return ResourceManager.GetString("Tile_TapToCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Toggle_Off {
            get {
                return ResourceManager.GetString("Toggle_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string Toggle_On {
            get {
                return ResourceManager.GetString("Toggle_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMI expects skies resulting in a UV-index as displayed on the figure below..
        /// </summary>
        public static string UVIndexHelpText1 {
            get {
                return ResourceManager.GetString("UVIndexHelpText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UV-index is a measurement for the intensity for the (skin-) harmful UV-radiation. At the midday sun on the equator it can be up to 15, where as in Denmark max 7 during the summer..
        /// </summary>
        public static string UVIndexHelpText2 {
            get {
                return ResourceManager.GetString("UVIndexHelpText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UV Index.
        /// </summary>
        public static string UVIndexMenuItem {
            get {
                return ResourceManager.GetString("UVIndexMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Number:.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebTV - 3-døgnsudsigten.
        /// </summary>
        public static string WebTV_3D {
            get {
                return ResourceManager.GetString("WebTV_3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebTV - Dagens Vejrudsigt.
        /// </summary>
        public static string WebTV_DMI {
            get {
                return ResourceManager.GetString("WebTV_DMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebTV - Sejlervejret.
        /// </summary>
        public static string WebTV_SEJL {
            get {
                return ResourceManager.GetString("WebTV_SEJL", resourceCulture);
            }
        }
    }
}
