//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMI.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMI.Service.Properties.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlqAO_r2pYHWEKTnYolKAITA9Ix8p5mHO26jZ2bWZbmn1FHMU6eEJKRgqnS2v-P4.
        /// </summary>
        internal static string BingMapsKey {
            get {
                return ResourceManager.GetString("BingMapsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://servlet.dmi.dk/byvejr/servlet/byvejr?by={0}&amp;tabel=dag3_9.
        /// </summary>
        internal static string Denmark_CityWeatherSevenDaysImage {
            get {
                return ResourceManager.GetString("Denmark_CityWeatherSevenDaysImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://servlet.dmi.dk/byvejr/servlet/byvejr_dag1?by={0}&amp;mode=long.
        /// </summary>
        internal static string Denmark_CityWeatherThreeDaysImage {
            get {
                return ResourceManager.GetString("Denmark_CityWeatherThreeDaysImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.dk/dmi/index/danmark/landsudsigten.htm.
        /// </summary>
        internal static string Denmark_CountryFeed {
            get {
                return ResourceManager.GetString("Denmark_CountryFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.dk/dmi/femdgn_dk.png.
        /// </summary>
        internal static string Denmark_CountryImage {
            get {
                return ResourceManager.GetString("Denmark_CountryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://servlet.dmi.dk/byvejr/servlet/byvejr?by={0}&amp;tabel=dag2_6_glfo&amp;lang=fo.
        /// </summary>
        internal static string FaroeIslands_CityWeatherSevenDaysImage {
            get {
                return ResourceManager.GetString("FaroeIslands_CityWeatherSevenDaysImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://servlet.dmi.dk/byvejr/servlet/byvejr_dag1?by={0}&amp;lang=fo&amp;mode=long.
        /// </summary>
        internal static string FaroeIslands_CityWeatherThreeDaysImage {
            get {
                return ResourceManager.GetString("FaroeIslands_CityWeatherThreeDaysImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.dk/dmi/index/faroerne.htm.
        /// </summary>
        internal static string FaroeIslands_CountryFeed {
            get {
                return ResourceManager.GetString("FaroeIslands_CountryFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://servlet.dmi.dk/byvejr/servlet/byvejr?by_gl={0}&amp;tabel=dag3_9.
        /// </summary>
        internal static string Greenland_CityWeatherSevenDaysImage {
            get {
                return ResourceManager.GetString("Greenland_CityWeatherSevenDaysImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://servlet.dmi.dk/byvejr/servlet/byvejr_dag1?by_gl={0}&amp;mode=long.
        /// </summary>
        internal static string Greenland_CityWeatherThreeDaysImage {
            get {
                return ResourceManager.GetString("Greenland_CityWeatherThreeDaysImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.dk/dmi/index/gronland/grover.htm.
        /// </summary>
        internal static string Greenland_CountryFeed {
            get {
                return ResourceManager.GetString("Greenland_CountryFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.dk/dmi/rss-nyheder.
        /// </summary>
        internal static string NewsFeed {
            get {
                return ResourceManager.GetString("NewsFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.dk/dmi/pollen-feed.xml.
        /// </summary>
        internal static string PollenFeed {
            get {
                return ResourceManager.GetString("PollenFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://servlet.dmi.dk/byvejr/servlet/pollen_dag1?by={0}.
        /// </summary>
        internal static string PollenImage {
            get {
                return ResourceManager.GetString("PollenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.dk/dmi/femdgn_bornholm.png.
        /// </summary>
        internal static string RegionalImage_Bornholm {
            get {
                return ResourceManager.GetString("RegionalImage_Bornholm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.dk/dmi/femdgn_ostjylland.png.
        /// </summary>
        internal static string RegionalImage_EastJytland {
            get {
                return ResourceManager.GetString("RegionalImage_EastJytland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.dk/dmi/femdgn_fyn.png.
        /// </summary>
        internal static string RegionalImage_Fyn {
            get {
                return ResourceManager.GetString("RegionalImage_Fyn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.dk/dmi/femdgn_vestjylland.png.
        /// </summary>
        internal static string RegionalImage_MiddleJytland {
            get {
                return ResourceManager.GetString("RegionalImage_MiddleJytland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.dk/dmi/femdgn_nordjylland.png.
        /// </summary>
        internal static string RegionalImage_NorthJytland {
            get {
                return ResourceManager.GetString("RegionalImage_NorthJytland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.dk/dmi/femdgn_kobenhavn.png.
        /// </summary>
        internal static string RegionalImage_NorthZealand {
            get {
                return ResourceManager.GetString("RegionalImage_NorthZealand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.dk/dmi/femdgn_sydjylland.png.
        /// </summary>
        internal static string RegionalImage_SouthJytland {
            get {
                return ResourceManager.GetString("RegionalImage_SouthJytland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.dk/dmi/femdgn_vestsjaelland.png.
        /// </summary>
        internal static string RegionalImage_SouthZealand {
            get {
                return ResourceManager.GetString("RegionalImage_SouthZealand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.dk/dmi/mobil/til_lands/lille-reg_born.htm.
        /// </summary>
        internal static string RegionalText_Bornholm {
            get {
                return ResourceManager.GetString("RegionalText_Bornholm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.dk/dmi/mobil/til_lands/lille-reg_ostj.htm.
        /// </summary>
        internal static string RegionalText_EastJytland {
            get {
                return ResourceManager.GetString("RegionalText_EastJytland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.dk/dmi/mobil/til_lands/lille-reg_fyn.htm.
        /// </summary>
        internal static string RegionalText_Fyn {
            get {
                return ResourceManager.GetString("RegionalText_Fyn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.dk/dmi/mobil/til_lands/lille-reg_midtvj.htm.
        /// </summary>
        internal static string RegionalText_MiddleJytland {
            get {
                return ResourceManager.GetString("RegionalText_MiddleJytland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.dk/dmi/mobil/til_lands/lille-reg_nord.htm.
        /// </summary>
        internal static string RegionalText_NorthJytland {
            get {
                return ResourceManager.GetString("RegionalText_NorthJytland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.dk/dmi/mobil/til_lands/lille-reg_kbhnord.htm.
        /// </summary>
        internal static string RegionalText_NorthZealand {
            get {
                return ResourceManager.GetString("RegionalText_NorthZealand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.dk/dmi/mobil/til_lands/lille-reg_sydson.htm.
        /// </summary>
        internal static string RegionalText_SouthJytland {
            get {
                return ResourceManager.GetString("RegionalText_SouthJytland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dmi.dk/dmi/mobil/til_lands/lille-reg_vssjlol.htm.
        /// </summary>
        internal static string RegionalText_SouthZealand {
            get {
                return ResourceManager.GetString("RegionalText_SouthZealand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://tv.dmi.dk/js/photos?raw.
        /// </summary>
        internal static string WebTVFeed {
            get {
                return ResourceManager.GetString("WebTVFeed", resourceCulture);
            }
        }
    }
}
